### ISSUE TITLE
Disk cache issues (panic)

### ISSUE THREAD

**Issue by stanistan** [stanistan/present-me#5]
This is nice for local dev so we don't keep hitting the API when restarting, but not great for prod, either bump the cache size, or drop the cache for an in memory one:

```
2021/04/14 14:37:31 http: panic serving 169.254.8.129:36169: 9837 bytes still won't fit in the cache! (max 10240 bytes)
goroutine 83 [running]:
net/http.(*conn).serve.func1(0xc0003f7b80)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xda3100, 0xc0003d1a40)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/peterbourgon/diskv.(*Diskv).ensureCacheSpaceWithLock(0xc0002a02d0, 0x266d, 0x993, 0x0)
	/go/pkg/mod/github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:611 +0x2cd
github.com/peterbourgon/diskv.(*Diskv).cacheWithLock(0xc0002a02d0, 0xc0000393e0, 0x13, 0xc0008eaa80, 0x266d, 0x4a80, 0x3edc6c3d6108, 0x14c6b00)
	/go/pkg/mod/github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:532 +0x3c
github.com/peterbourgon/diskv.(*Diskv).cacheWithoutLock(0xc0002a02d0, 0xc0000393e0, 0x13, 0xc0008eaa80, 0x266d, 0x4a80, 0x0, 0x0)
	/go/pkg/mod/github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:550 +0xb9
github.com/peterbourgon/diskv.(*siphon).Read(0xc0002c2900, 0xc00092466d, 0x993, 0x993, 0x16d, 0x0, 0x0)
	/go/pkg/mod/github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:386 +0x13d
io.ReadAll(0x3edc45367b18, 0xc0003d1a30, 0xc0003d1a30, 0x3edc45367b18, 0xc0003d1a30, 0xc0003d1a30, 0x0)
	/usr/local/go/src/io/io.go:633 +0xdf
io/ioutil.ReadAll(...)
	/usr/local/go/src/io/ioutil/ioutil.go:27
github.com/peterbourgon/diskv.(*Diskv).Read(0xc0002a02d0, 0xc0000393e0, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:266 +0x110
github.com/stanistan/present-me/internal/cache.(*Cache).Read(0xc0003d1640, 0xd929e0, 0xc0006db998, 0xd72b00, 0xc0006db980, 0x8bb2c97000, 0x28, 0x28, 0x3edc6c3d6108)
	/go/src/app/internal/cache/cache.go:87 +0x86
github.com/stanistan/present-me/internal/cache.(*Cache).Apply(0xc0003d1640, 0x14d52c0, 0xc0006cde00, 0xd72b00, 0xc0006db980, 0xd929e0, 0xc0006db998, 0xc0002c2720, 0x0, 0x0)
	/go/src/app/internal/cache/cache.go:54 +0x3a5
github.com/stanistan/present-me.(*GH).ListReviewComments(0xc0000b22e0, 0x14d52c0, 0xc0006cde00, 0xc0006cdda0, 0xc000722a80, 0x0, 0x0, 0xd1faf1, 0x14d52c0)
	/go/src/app/github.go:116 +0x165
github.com/stanistan/present-me.(*GH).FetchReviewModel(0xc0000b22e0, 0x14d52c0, 0xc0006cde00, 0xc0006cdda0, 0x40d99b, 0xc00012efc0, 0x90)
	/go/src/app/github.go:146 +0x125
github.com/stanistan/present-me.(*ReviewParams).Model(...)
	/go/src/app/params.go:93
main.doMD.func1.1(0xc00012efc0, 0xe87560)
	/go/src/app/cmd/server/main.go:119 +0xbe
main.handle(0x14d3cc0, 0xc0005b0380, 0xc0006489d0)
	/go/src/app/cmd/server/main.go:130 +0x2b
main.doMD.func1(0x14d3cc0, 0xc0005b0380, 0xc000543200)
	/go/src/app/cmd/server/main.go:113 +0x96
net/http.HandlerFunc.ServeHTTP(0xc000601a88, 0x14d3cc0, 0xc0005b0380, 0xc000543200)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002ac480, 0x14d3cc0, 0xc0005b0380, 0xc000543000)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc0005b0000, 0x14d3cc0, 0xc0005b0380, 0xc000543000)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0003f7b80, 0x14d52c0, 0xc000722480)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
```

**Comment by stanistan** [comment]
Fixed in https://github.com/stanistan/present-me/commit/c858774a7446c1dc6f20b35fd767c949885080f6
